# src/config.py

# angles in degrees
SQUAT_KNEE_DOWN_THRESHOLD = 95    
SQUAT_KNEE_UP_THRESHOLD = 155    

ARM_RAISE_UP_THRESHOLD = 160      
ARM_RAISE_DOWN_THRESHOLD = 45

SIDE_BEND_TILT_THRESHOLD = 25

LUNGE_FRONT_KNEE_DOWN_THRESHOLD = 90 
LUNGE_FRONT_KNEE_UP_THRESHOLD = 165 

# FPS smoothing for rep detection
SMOOTHING_WINDOW = 5